name: Release Package

on:
  push:
    tags:
      - "v*"

jobs:
  publish-react-rich-input:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/react-rich-editor

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build all packages
        run: bunx turbo run build

      - name: Rename package-name for GitHub Packages
        run: |
          jq '.name = "@amiry-jd/react-rich-editor"' package.json > tmp.json && mv tmp.json package.json

      - name: Configure npm for GitHub Packages
        run: |
          echo "@amiry-jd:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> ~/.npmrc

      - name: Check .npmrc
        run: cat ~/.npmrc

      - name: Publish to GitHub Packages
        run: |
          echo "NODE_AUTH_TOKEN is:"
          echo $NODE_AUTH_TOKEN
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Clean up .npmrc
        run: rm ~/.npmrc

      - name: Rename package-name for npm Packages
        run: |
          jq '.name = "react-rich-editor"' package.json > tmp.json && mv tmp.json package.json

      - name: Configure npm for npmjs packages
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: |
          echo "NODE_AUTH_TOKEN is:"
          echo $NODE_AUTH_TOKEN
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Clean up .npmrc
        run: rm ~/.npmrc

  publish-nect-rich-input:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/next-rich-editor

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build all packages
        run: bunx turbo run build

      - name: Rename package-name for GitHub Packages
        run: |
          jq '.name = "@amiry-jd/next-rich-editor"' package.json > tmp.json && mv tmp.json package.json

      - name: Configure npm for GitHub Packages
        run: |
          echo "@amiry-jd:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> ~/.npmrc

      - name: Check .npmrc
        run: cat ~/.npmrc

      - name: Publish to GitHub Packages
        run: |
          echo "NODE_AUTH_TOKEN is:"
          echo $NODE_AUTH_TOKEN
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Clean up .npmrc
        run: rm ~/.npmrc

      - name: Rename package-name for npm Packages
        run: |
          jq '.name = "next-rich-editor"' package.json > tmp.json && mv tmp.json package.json

      - name: Configure npm for npmjs packages
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: |
          echo "NODE_AUTH_TOKEN is:"
          echo $NODE_AUTH_TOKEN
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Clean up .npmrc
        run: rm ~/.npmrc
